name: init-0-ubuntu18

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: init-0-ubuntu18
        echo Add other actions to build,
        echo test, and deploy your project.
